server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://8.134.219.139:3306/niftiihub?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: niftiihub
    password: sdfhh893whfj09ewj0w9j89shfh908q2h89hfSsFESFE684f8es
    driver-class-name: com.mysql.cj.jdbc.Driver


#  data:
#    redis:
#      host: 127.0.0.1
#      database: 0
#      port: 6379
#
#
#logging:
#  level:
#    root: info
#
#minio:
#  endpoint: http://127.0.0.1:9000
#  accessKey: testGseek
#  secretKey: 287dba04f2f02025a7a048bc356a78a017e90c7e
#  bucketName: gtest1
#
## 自定义参数
#custom:
#  # aes加密key值，在PasswordUtil#init中用到
#  encryptKey: "test1encrypt2key"
#
